// 歯型。わざと壊して、落ちるべき検査が落ちることを確かめる表。
//
// **テストが通ることと、テストが守っていることは別。**この repo には
// 「宣言しただけで代入を忘れると E2E が静かに嘘をつく」「toHaveScreenshot の
// 通ったは変わっていないではない」という記録がある。どちらも「通っている
// のに守れていない」形だった。
//
// ここに 1 行足すと、その壊し方が毎回試される。`docs/lessons.md` に書いた
// 教訓のうち、機械にできるものはここへ落とす。**教訓を実行可能な形にする。**
//
// 表そのものが腐るので、`tests/tools/mutate.test.ts` が 18 秒の単体テストで
// 健全性を守る。`find` が対象ファイルにちょうど 1 回現れること、`expect` の
// テストが実在すること、`lesson` が `docs/lessons.md` にあること。定数を
// リネームしただけで `find` が当たらなくなり、変異を 1 度も走らせずに気づける。
//
// 変異の型は 6 つ。定数の摂動、比較の反転、条件の固定、文の削除、
// 表の行の削除、符号の反転。段 4 で 6 つ全部が埋まった。

/**
 * @type {import('./bite-marks.d.mts').BiteMark[]}
 */
export const BITE_MARKS = [
  // ── 表の行の削除 ────────────────────────────────────────────
  {
    id: 'help-drop-keyf',
    kind: '表の行の削除',
    file: 'src/input/keyboard.ts',
    find: "  { keys: 'F', action: 'ミサイル', codes: ['KeyF'] },\n",
    replace: '',
    expect: 'tests/input/controlHelp.test.ts',
    lesson: '操作説明と実装のキー割り当てがずれる',
  },
  {
    id: 'help-drop-escape',
    kind: '表の行の削除',
    file: 'src/input/keyboard.ts',
    find: "  { keys: 'Escape', action: 'ポーズ', codes: ['Escape'] },\n",
    replace: '',
    expect: 'tests/input/controlHelp.test.ts',
    lesson: 'ポーズ（Escape）が `CONTROL_HELP` に載っていない',
  },
  {
    id: 'layering-drop-rule',
    kind: '表の行の削除',
    file: 'tests/sim/layering.test.ts',
    find: "  { pattern: /Math\\.random\\s*\\(/, reason: 'Math.random（Rng を使うこと）' },\n",
    replace: '',
    expect: 'tests/sim/layering.test.ts',
    lesson: '`src/sim` から three を import しても、実行するまで気づけない',
  },

  // ── 文の削除 ────────────────────────────────────────────────
  {
    id: 'help-drop-keyc-impl',
    kind: '文の削除',
    file: 'src/input/keyboard.ts',
    find: "    this.input.deployFlare = this.pressed.has('KeyC')\n",
    replace: '',
    expect: 'tests/input/controlHelp.test.ts',
    lesson: '操作説明と実装のキー割り当てがずれる',
  },
  {
    id: 'hook-drop-assign',
    kind: '文の削除',
    file: 'src/main.ts',
    find: '    hook.missilesLeft = currentWorld.combat.missilesLeft\n',
    replace: '',
    expect: 'tests/render/testHook.test.ts',
    lesson: '`TestHook` に項目を足したのに `publish` の代入だけ抜け',
  },

  // ── 定数の摂動 ──────────────────────────────────────────────
  {
    id: 'docs-drag-factor',
    kind: '定数の摂動',
    file: 'docs/flight-model.md',
    find: 'k  = 1 / (π AR e) = 0.099630',
    replace: 'k  = 1 / (π AR e) = 0.1158',
    expect: 'tests/tools/docsNumbers.test.ts',
    lesson: '誘導抗力係数が `0.1158` のままだった',
  },
  {
    id: 'scenes-change-coverage',
    kind: '定数の摂動',
    file: 'tests/e2e/scenes.mjs',
    find: "name: 'clouds-dense', script: 'level', frame: 480, hour: 16, coverage: 0.8",
    replace: "name: 'clouds-dense', script: 'level', frame: 480, hour: 16, coverage: 0.3",
    expect: 'tests/tools/scenes.test.ts',
    lesson: '画素比較の道具と基準画像を撮る側で雲量の既定が違った',
  },
  {
    id: 'lift-slope',
    kind: '定数の摂動',
    file: 'src/sim/flightModel.ts',
    find: '  liftSlope: 4.19,',
    replace: '  liftSlope: 4.5,',
    expect: 'tests/sim/flightModel.test.ts',
    why: '揚力傾斜は最大揚力係数とコーナー速度の両方に効く。動かして誰も気づかないなら、その 2 つを見張れていない',
  },
  {
    id: 'seeker-acquire-angle',
    kind: '定数の摂動',
    file: 'src/sim/weapons/lock.ts',
    find: 'export const SEEKER_ACQUIRE_ANGLE = 20 * DEG',
    replace: 'export const SEEKER_ACQUIRE_ANGLE = 30 * DEG',
    expect: 'tests/sim/lock.test.ts',
    why: '捕捉の視野。広げて誰も気づかないなら、境界を見張れていない',
  },
  // ── Stryker の掃引が見つけた穴（段 4）────────────────────────
  // 生存していた変異をそのまま歯型にする。13 分の掃引を毎回は回せないので、
  // **見つかったものだけ 1 秒の検査へ引き上げる。**
  {
    id: 'level-gain-divide',
    kind: '符号の反転',
    file: 'src/sim/assist.ts',
    find:
      '  if (input.roll === 0 && Math.abs(view.bank) > LEVEL_DEADZONE) {\n' +
      '    roll = clamp(-view.bank * LEVEL_GAIN, -1, 1)',
    replace:
      '  if (input.roll === 0 && Math.abs(view.bank) > LEVEL_DEADZONE) {\n' +
      '    roll = clamp(-view.bank / LEVEL_GAIN, -1, 1)',
    expect: 'tests/sim/assist.test.ts',
    lesson: '符号と向きだけを見ていると、掛け算を割り算に変えても落ちない',
  },
  {
    id: 'recover-pitch-boundary',
    kind: '比較の反転',
    file: 'src/sim/assist.ts',
    find: '    pitch = Math.abs(view.bank) < 0.5 ? 1 : 0.2',
    replace: '    pitch = Math.abs(view.bank) <= 0.5 ? 1 : 0.2',
    expect: 'tests/sim/assist.test.ts',
    lesson: '符号と向きだけを見ていると、掛け算を割り算に変えても落ちない',
  },
  {
    id: 'dlz-overtook-never',
    kind: '定数の摂動',
    file: 'src/sim/weapons/dlz.ts',
    find: '    if (speed > targetSpeedAway) overtook = true',
    replace: '    if (speed > targetSpeedAway) overtook = false',
    expect: 'tests/sim/dlz.test.ts',
    lesson: '追い越しの判定と DLZ の clamp が丸ごと素通りしていた',
  },
  {
    id: 'dlz-drop-clamp',
    kind: '文の削除',
    file: 'src/sim/weapons/dlz.ts',
    find: '  if (out.rNe > out.rMax) out.rNe = out.rMax\n',
    replace: '',
    expect: 'tests/sim/dlz.test.ts',
    lesson: '追い越しの判定と DLZ の clamp が丸ごと素通りしていた',
  },

  {
    id: 'standard-roll-gain',
    kind: '定数の摂動',
    file: 'src/sim/assist.ts',
    find: 'const STANDARD_ROLL_GAIN = 0.7',
    replace: 'const STANDARD_ROLL_GAIN = 1.0',
    expect: 'tests/sim/assist.test.ts',
    why: 'スタンダード操作のロール抑制。1.0 はエキスパートと同じ。補助が効いていることを数で見張れているか',
  },

  // ── 比較の反転 ──────────────────────────────────────────────
  {
    id: 'fixed-step-boundary',
    kind: '比較の反転',
    file: 'src/sim/loop.ts',
    find: '    while (this.accumulator >= this.dt) {',
    replace: '    while (this.accumulator > this.dt) {',
    expect: 'tests/sim/loop.test.ts',
    why: '固定ステップの境界。ちょうど 1 ステップぶん溜まったときに進めなくなる。「半ステップ 2 回で 1 ステップ」がこれを見張っているはず',
  },

  {
    id: 'escape-uses-event-key',
    kind: '比較の反転',
    file: 'src/main.ts',
    find: "    if (event.code !== 'Escape') return",
    replace: "    if (event.key !== 'Escape') return",
    expect: 'tests/input/controlHelp.test.ts',
    lesson: 'ポーズ（Escape）が `CONTROL_HELP` に載っていない',
  },

  // ── 条件の固定 ──────────────────────────────────────────────
  {
    id: 'help-scan-one-file',
    kind: '条件の固定',
    file: 'tests/input/controlHelp.test.ts',
    find: "    .filter(({ source }) => source.includes('keydown') || source.includes('KeyboardEvent'))",
    replace: "    .filter(({ path }) => path.endsWith('keyboard.ts'))",
    expect: 'tests/input/controlHelp.test.ts',
    lesson: 'ポーズ（Escape）が `CONTROL_HELP` に載っていない',
  },
  {
    id: 'aoa-limiter-always-off',
    kind: '条件の固定',
    file: 'src/sim/aircraft.ts',
    find: '    const useLimiter = options.aoaLimiter !== false',
    replace: '    const useLimiter = false',
    expect: 'tests/sim/aircraft.test.ts',
    why: '迎角制限器を常に切る。既定で効いていることを見張れているか。切れるようにしてある機能は、既定側も見張らないと片側しか通らない',
  },
  {
    id: 'shadow-tiles-drop-length-guard',
    kind: '文の削除',
    file: 'src/render/clouds/geometry.ts',
    find: '  if (bytes.length < width * height * 4) return []\n',
    replace: '',
    expect: 'tests/render/shadowHistogram.test.ts',
    why: '読み戻せていない絵を 0 で埋めて返すと、GLSL 版との突き合わせが「一致した」になる。長さが足りないときは空を返すこと',
  },
  {
    id: 'shadow-tiles-single-cell',
    kind: '定数の摂動',
    file: 'src/render/clouds/geometry.ts',
    find: 'export const SHADOW_TILES = 4',
    replace: 'export const SHADOW_TILES = 1',
    expect: 'tests/render/shadowHistogram.test.ts',
    lesson: '分布は配置を見ない',
  },
  {
    id: 'shadow-inputs-drop-empty-check',
    kind: '文の削除',
    file: 'src/render/clouds/shadowInputs.ts',
    find: "  if (parts.some((p) => p.trim() === '')) return null\n",
    replace: '',
    expect: 'tests/render/shadowInputs.test.ts',
    why: "`Number('')` は 0 を返すので、末尾の欠けた `?shadowinputs=` が「中心 Z が 0」として黙って通る。TSL 版と GLSL 版が別の入力で焼いたものを比べることになる",
  },
  {
    id: 'readback-drop-stride-guard',
    kind: '文の削除',
    file: 'src/render/pipeline/readback.ts',
    find: `  if (!Number.isInteger(stride) || stride < rowBytes) {
    throw new Error(
      \`読み戻しの行の間隔が読めない: 長さ \${total}、幅 \${width}、高さ \${height}\`,
    )
  }

`,
    replace: '',
    expect: 'tests/render/readback.test.ts',
    lesson: '読み戻しの向きと原点がバックエンドで違う',
  },
  {
    id: 'march-samples-drop-high-byte',
    kind: '文の削除',
    file: 'src/render/clouds/marchProbe.ts',
    find: 'bytes[i * 4]! * 256 + bytes[i * 4 + 1]!',
    replace: 'bytes[i * 4 + 1]!',
    expect: 'tests/render/marchProbe.test.ts',
    why: '密度サンプル数は R と G に 16bit で詰めてある。上位バイトを落とすと 256 以上が全部同じに見え、歩き方の違いが埋もれる',
  },
  {
    id: 'march-camera-below-slab',
    kind: '定数の摂動',
    file: 'src/render/clouds/marchProbe.ts',
    find: '  positionY: 2000,\n  positionZ: 0,',
    replace: '  positionY: 900,\n  positionZ: 0,',
    expect: 'tests/render/marchProbe.test.ts',
    lesson: '通っていない枝は検査されない',
  },
  {
    id: 'byte-difference-drop-length-guard',
    kind: '文の削除',
    file: 'src/render/clouds/marchProbe.ts',
    find: `  if (a.length !== b.length) {
    return { differing: Number.POSITIVE_INFINITY, max: Number.POSITIVE_INFINITY }
  }
`,
    replace: '',
    expect: 'tests/render/marchProbe.test.ts',
    why: '長さの違う 2 枚を先頭だけ比べると「違うバイト 0 個」になる。読み戻せていない絵を一致したと読む形を作らない',
  },
  {
    id: 'byte-difference-ignore-floor',
    kind: '条件の固定',
    file: 'src/render/clouds/marchProbe.ts',
    find: '    if (d > floor) differing++',
    replace: '    if (d > 0) differing++',
    expect: 'tests/render/marchProbe.test.ts',
    lesson: '「動いたバイト数」の閾値を雑音が支えていた',
  },
  {
    id: 'detail-judge-mask-noise',
    kind: '条件の固定',
    file: 'tools/detail-judge.mjs',
    find: 'if (Math.abs(a[p * 4 + c] - b[p * 4 + c]) > floor) {',
    replace: 'if (Math.abs(a[p * 4 + c] - b[p * 4 + c]) > 0) {',
    expect: 'tests/tools/detailJudge.test.ts',
    lesson: '「動いたバイト数」の閾値を雑音が支えていた',
  },
  {
    id: 'detail-judge-last-component',
    kind: '条件の固定',
    file: 'tools/detail-judge.mjs',
    find: '    if (size > bestSize) {',
    replace: '    if (size > 0) {',
    expect: 'tests/tools/detailJudge.test.ts',
    why: '機体を消すと雲の描かれ方も少し変わり、aircraft-close では機体の上の空に 146 画素の塊が出た',
  },
  {
    id: 'detail-judge-no-dim-guard',
    kind: '条件の固定',
    file: 'tools/detail-judge.mjs',
    find: '  const dim = medianRise < -10',
    replace: '  const dim = false',
    expect: 'tests/tools/detailJudge.test.ts',
    why: '粗さの中心を 0.45 へ下げた版は 3 構図で中央値が −16〜−18%。上だけ縛ると暗くなった絵を通す',
  },
  {
    id: 'surface-detail-ignore-preset',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeAircraftMaterial.ts',
    find: "    if (detail === 'procedural' && wantsSurfaceDetail(source, copy)) {",
    replace: '    if (wantsSurfaceDetail(source, copy)) {',
    expect: 'tests/render/nodeAircraftMaterial.test.ts',
    why: 'none のプリセット（low と medium）と `?materialdetail=none` の基準で細部が入ると、判定道具の基準そのものが崩れる',
  },
  {
    id: 'surface-detail-transparent',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeAircraftMaterial.ts',
    find: '  if (source.transparent) return false\n',
    replace: '',
    expect: 'tests/render/nodeAircraftMaterial.test.ts',
    why: 'F-16 のキャノピーは透明。溝を掘っても意味が無く、遮蔽で暗くなる',
  },
  {
    id: 'surface-detail-no-occlusion',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeAircraftMaterial.ts',
    find: '  material.aoNode = float(1).sub(line.mul(d.lineOcclusion))\n',
    replace: '',
    expect: 'tests/render/nodeAircraftMaterial.test.ts',
    lesson: '溝の粗さを上げたら溝が光った',
  },
  {
    id: 'mutate-ignore-overridden',
    kind: '文の削除',
    file: 'playwright.config.ts',
    find: '      testIgnore: [/node-fallback\\.spec\\.ts/, ...MUTATE_ONLY, ...NODE_PATH_DUPLICATE],',
    replace: '      testIgnore: [/node-fallback\\.spec\\.ts/, ...NODE_PATH_DUPLICATE],',
    expect: 'tests/tools/e2eConfig.test.ts',
    lesson: 'project の `testIgnore` は上位の `testIgnore` を上書きする',
  },
  {
    id: 'node-path-run-twice',
    kind: '文の削除',
    file: 'playwright.config.ts',
    find: '      testIgnore: [/node-fallback\\.spec\\.ts/, ...MUTATE_ONLY, ...NODE_PATH_DUPLICATE],',
    replace: '      testIgnore: [/node-fallback\\.spec\\.ts/, ...MUTATE_ONLY],',
    expect: 'tests/tools/e2eConfig.test.ts',
    why: '既定が node のあいだ、主の project と chromium-node は同じ引数・同じ宣言。両方で回すと 25 本を 2 回流す（CPU の 7.1%）',
  },
  {
    id: 'scene-pass-no-mrt',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeOutput.ts',
    find: "        ...(normals ? { normal: directionToColor(normalView) } : {}),\n",
    replace: '',
    expect: 'tests/render/scenePass.test.ts',
    why: 'SSR が読む法線の面が作られない。getTextureNode だけでは 2 本目の出力を書き出さない',
  },
  {
    id: 'terrain-fragment-node',
    kind: '条件の固定',
    file: 'src/render/terrain/nodeMaterials.ts',
    find: '  ;(material as unknown as { outputNode: unknown }).outputNode =\n    terrainSurfaceNode(',
    replace: '  ;(material as unknown as { fragmentNode: unknown }).fragmentNode =\n    terrainSurfaceNode(',
    expect: 'tests/render/surfaceMrt.test.ts',
    lesson: '`fragmentNode` を持つ材質には MRT が当たらない',
  },
  {
    id: 'flame-mrt-missing',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeFlameMaterial.ts',
    find: '    ;(copy as THREE.Material & { mrtNode: unknown }).mrtNode = mrt({ emissive: output })\n',
    replace: '',
    expect: 'tests/render/nodeFlameMaterial.test.ts',
    why: '炎が emissive を書かないと、場面の既定の 0 のままで選択的ブルームが何も拾わない。例外もコンソールも出ない',
  },
  {
    id: 'afterburner-ignore-factory',
    kind: '条件の固定',
    file: 'src/render/aircraft/afterburner.ts',
    find: '  const innerMaterial = material(\n',
    replace: '  const innerMaterial = keepFlameMaterial(\n',
    expect: 'tests/render/nodeFlameMaterial.test.ts',
    why: '作り手の写しを使わないと、内炎だけが MRT を書かず、不透明度も写しに届かない',
  },
  {
    id: 'hot-core-lingers',
    kind: '定数の摂動',
    file: 'src/sim/effects.ts',
    find: 'export const HOT_CORE_HOLD = 0.1',
    replace: 'export const HOT_CORE_HOLD = 0.3',
    expect: 'tests/sim/effects.test.ts',
    why: '白い芯が残ると火球が白い塊に見える。赤い芯（CORE_HOLD 0.18 秒）より先に消えることを見張る',
  },
  {
    id: 'canopy-clearcoat-ignore-switch',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeAircraftMaterial.ts',
    find: '    if (clearcoat && isCanopyGlass(source, copy)) {',
    replace: '    if (isCanopyGlass(source, copy)) {',
    expect: 'tests/render/nodeAircraftMaterial.test.ts',
    why: 'low と `?canopyclearcoat=0` の基準でも層が乗ると、判定道具の基準そのものが崩れる',
  },
  {
    id: 'canopy-glass-any-physical',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeAircraftMaterial.ts',
    find: '  return source.map == null\n}',
    replace: '  return true\n}',
    expect: 'tests/render/nodeAircraftMaterial.test.ts',
    why: '塗装のある physical の材質に層が乗ると、外板の一部が鏡になる（計画書の「鏡の失敗の再演」）',
  },
  {
    id: 'judge-gloss-nan',
    kind: '比較の反転',
    file: 'tools/detail-judge.mjs',
    find: '  const dull = !(regionRise >= GLOSS_RISE)',
    replace: '  const dull = regionRise < GLOSS_RISE',
    expect: 'tests/tools/detailJudge.test.ts',
    why: '変わった場所が無いと中央値は NaN。NaN との比較はすべて false なので、< で書くと「艶が出た」になる',
  },
  {
    id: 'height-probe-step-on-grid',
    kind: '定数の摂動',
    file: 'src/render/terrain/heightProbe.ts',
    find: 'step: { x: 1237.3, z: 1511.7 }',
    replace: 'step: { x: 1248, z: 1536 }',
    expect: 'tests/render/heightProbe.test.ts',
    why: '刻みをテクセル 48 m の倍数にすると双三次が t = 0 になり、焼いた値をそのまま返すだけの検査になる。補間の途中を通さないと写し間違いが見えない',
  },
  {
    id: 'height-error-drop-nan-guard',
    kind: '文の削除',
    file: 'src/render/terrain/heightProbe.ts',
    find: '    if (!Number.isFinite(d)) return Number.POSITIVE_INFINITY\n',
    replace: '',
    expect: 'tests/render/heightProbe.test.ts',
    why: 'NaN との差は比較が常に false になるので、最大のずれ 0 として通ってしまう。読み戻せていない点を一致したと読む形を作らない',
  },
  {
    id: 'surface-probe-flat-region',
    kind: '定数の摂動',
    file: 'src/render/terrain/surfaceProbe.ts',
    find: 'origin: { x: -1708, z: -15100 },',
    replace: 'origin: { x: 18000, z: 18000 },',
    expect: 'tests/render/surfaceProbe.test.ts',
    lesson: '通っていない枝は検査されない',
  },
  {
    id: 'surface-probe-sun-flat',
    kind: '定数の摂動',
    file: 'src/render/terrain/surfaceProbe.ts',
    find: 'unit(0.42, 0.63, -0.65)',
    replace: 'unit(0.42, 0.03, -0.65)',
    expect: 'tests/render/surfaceProbe.test.ts',
    why: '太陽が低いと雲影の足元へのずらしが `sunDirectionWorld.y > 0.05` の枝を通らない。標高のある地表で影の位置がずれる写し間違いが見えなくなる',
  },
  {
    id: 'surface-shadow-uniform',
    kind: '定数の摂動',
    file: 'src/render/terrain/surfaceProbe.ts',
    find: 'data[y * size + x] = Math.round(Math.min(1, stripe * blocks) * 255)',
    replace: 'data[y * size + x] = 128',
    expect: 'tests/render/surfaceProbe.test.ts',
    why: '雲影が一様だと、引く位置を間違えても同じ値が返って一致してしまう',
  },
  {
    id: 'shader-reserved-word',
    kind: '定数の摂動',
    file: 'src/render/terrain/shaders/waterSurface.glsl',
    find: 'out float applied) {',
    replace: 'out float active) {',
    expect: 'tests/render/shaderReserved.test.ts',
    lesson: 'GLSL の予約語を識別子に使うとコンパイルが黙って落ちる',
  },
  {
    id: 'overlay-probe-never-opaque',
    kind: '定数の摂動',
    file: 'src/render/overlayProbe.ts',
    find: 'export const OVERLAY_PROBE_FULL_COLUMN = 47',
    replace: 'export const OVERLAY_PROBE_FULL_COLUMN = 64',
    expect: 'tests/render/overlayProbe.test.ts',
    lesson: '通っていない枝は検査されない',
  },
  {
    id: 'overlay-composite-line-drift',
    kind: '定数の摂動',
    file: 'src/render/overlayProbe.ts',
    find: `export const OVERLAY_COMPOSITE_GLSL =
  'outputColor.rgb = outputColor.rgb * (1.0 - overlay.a) + overlay.rgb;'`,
    replace: `export const OVERLAY_COMPOSITE_GLSL =
  'outputColor.rgb = outputColor.rgb * (1.0 - overlay.r) + overlay.rgb;'`,
    expect: 'tests/render/overlayProbe.test.ts',
    why: '合成の式は takram の断片シェーダから写したもの。写しが原本から離れても、GLSL 版と TSL 版が同じ写し間違いをしていればバイトは一致する。原本との照合が働かなくなる形を作らない',
  },
  {
    id: 'overlay-marker-drop-other',
    kind: '文の削除',
    file: 'src/render/overlayProbe.ts',
    find: '    else other++\n',
    replace: '',
    expect: 'tests/render/overlayProbe.test.ts',
    why: 'どちらの枝の色でもない画素を数えないと、枝の書き分けが壊れていても片方の数が合っているだけで通る',
  },
  {
    id: 'node-frame-no-advance',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeBuild.ts',
    find: '  holder._nodes.nodeFrame.frameId++',
    replace: '  void holder',
    expect: 'tests/render/nodeFrame.test.ts',
    lesson: '手で `render()` を回すと `FRAME` 型のノード更新が 1 度しか走らない',
  },
  {
    id: 'solar-elevation-skip-frame',
    kind: '文の削除',
    file: 'src/render/atmosphereNodes.ts',
    find: '  const localUpECEF = new Vector3(0, 1, 0).transformDirection(worldToECEF)',
    replace: '  const localUpECEF = new Vector3(0, 1, 0)',
    expect: 'tests/render/solarFrame.test.ts',
    why: 'ワールドの Y と ECEF の Z は別物。行列を通さずに内積を取ると太陽高度が緯度ぶん（35.6 度）ずれる。絵では夕方の色が少し違うようにしか見えず、雲のライティングも一緒にずれるので切り分けられない',
  },
  {
    id: 'node-backend-version-from-kind',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeBackend.ts',
    find: '    gl === null ? 0 : /WebGL 2/.test(gl.getParameter(gl.VERSION) as string) ? 2 : 1',
    replace: '    isWebGPU ? 0 : 2',
    expect: 'tests/render/nodeBackend.test.ts',
    lesson: '継ぎ目を作る作業がそのまま見張りを外す',
  },
  {
    id: 'node-backend-drain-from-kind',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeBackend.ts',
    find: '      return gl !== null',
    replace: '      return !isWebGPU',
    expect: 'tests/render/nodeBackend.test.ts',
    lesson: '継ぎ目を作る作業がそのまま見張りを外す',
  },
  {
    id: 'f18e-aileron-threshold',
    kind: '条件の固定',
    file: 'tools/f18e-parts.mjs',
    find: 'near(p.x, 2.47, 0.4) && near(p.absZ, 5.41, 0.5) && p.z > 0',
    replace: 'near(p.x, 2.47, 2.0) && near(p.absZ, 5.41, 2.0) && p.z > 0',
    expect: 'tests/tools/f18eParts.test.ts',
    why: '舵面を名前ではなく位置で当てているので、閾値が広いと隣の部品を巻き込む。実測で 5 倍に広げると 1 件が 3 件になる',
  },
  {
    id: 'f18e-aileron-is-outer-panel',
    kind: '条件の固定',
    file: 'tools/f18e-parts.mjs',
    find: '    match: (p) => near(p.x, 2.47, 0.4) && near(p.absZ, 5.41, 0.5) && p.z > 0 && thin(p, 0.4),',
    replace: '    match: (p) => near(p.x, 1.43, 0.4) && near(p.absZ, 5.41, 0.5) && p.z > 0 && thin(p, 0.4),',
    expect: 'tests/tools/f18eParts.test.ts',
    lesson: '「左右対称の薄板が 1 件だけ当たる」は舵面であることの証明にならない',
  },
  {
    id: 'f18e-aileron-side',
    kind: '条件の固定',
    file: 'tools/f18e-parts.mjs',
    find: '    match: (p) => near(p.x, 2.47, 0.4) && near(p.absZ, 5.41, 0.5) && p.z < 0 && thin(p, 0.4),',
    replace: '    match: (p) => near(p.x, 2.47, 0.4) && near(p.absZ, 5.41, 0.5) && p.z > 0 && thin(p, 0.4),',
    expect: 'tests/tools/f18eParts.test.ts',
    lesson: '幾何だけで当てていると左右を取り違えても検査は通る',
  },
  {
    id: 'f18e-gear-overlap',
    kind: '条件の固定',
    file: 'tools/f18e-parts.mjs',
    find: '  match: (p) => p.y < -0.6 || (p.y < -0.5 && p.sizeY > 0.8),',
    replace: '  match: (p) => p.y < 0.6 || (p.y < -0.5 && p.sizeY > 0.8),',
    expect: 'tests/tools/f18eParts.test.ts',
    why: '降着装置の範囲が広いと舵面を巻き込む。巻き込むと `gear` を隠したときに舵が消える',
  },
  {
    id: 'sprite-node-depth-write',
    kind: '条件の固定',
    file: 'src/render/weapons/spriteNodes.ts',
    find: '  material.depthWrite = opaqueCore',
    replace: '  material.depthWrite = false',
    expect: 'tests/render/radialSpriteFactory.test.ts',
    lesson: '断片のバイトが一致しても材質が一致しているとは限らない',
  },
  {
    id: 'sprite-node-blending',
    kind: '条件の固定',
    file: 'src/render/weapons/spriteNodes.ts',
    find: '  material.blending = options.additive ? AdditiveBlending : NormalBlending',
    replace: '  material.blending = NormalBlending',
    expect: 'tests/render/radialSpriteFactory.test.ts',
    lesson: '断片のバイトが一致しても材質が一致しているとは限らない',
  },
  {
    id: 'aircraft-material-null-guard',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeAircraftMaterial.ts',
    find: '    const copy = renderer.library.fromMaterial(source) ?? source',
    replace: '    const copy = renderer.library.fromMaterial(source)!',
    expect: 'tests/render/nodeAircraftMaterial.test.ts',
    why: 'fromMaterial はクラスが無い型で null を返す。例外もコンソールも出ないので、素通しするとそのメッシュだけが消える',
  },
  {
    id: 'aircraft-material-share',
    kind: '条件の固定',
    file: 'src/render/aircraft/model.ts',
    find: '    const cached = made.get(source)',
    replace: '    const cached = undefined',
    expect: 'tests/render/aircraftMaterial.test.ts',
    why: '同じ材質を参照するメッシュごとに写すと材質の実体が増え、描画の状態切り替えが増える',
  },
  {
    id: 'node-timer-keep-zero',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeTimer.ts',
    find: "if (typeof ms === 'number' && Number.isFinite(ms) && ms > 0) {",
    replace: "if (typeof ms === 'number' && Number.isFinite(ms)) {",
    expect: 'tests/render/nodeTimer.test.ts',
    lesson: '0 を数に混ぜると最小値が 0 になる',
  },
  {
    id: 'node-timer-overlap-resolve',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeTimer.ts',
    find: `      if (waiting > 0) {
        dropped++
        return
      }

`,
    replace: '',
    expect: 'tests/render/nodeTimer.test.ts',
    lesson: '解決を決着前に重ねると前の回の値が返る',
  },
  {
    id: 'sprite-probe-opacity-below-core-cut',
    kind: '定数の摂動',
    file: 'src/render/weapons/spriteProbe.ts',
    find: 'export const SPRITE_PROBE_OPACITY = 0.8',
    replace: 'export const SPRITE_PROBE_OPACITY = 0.4',
    expect: 'tests/render/spriteProbe.test.ts',
    lesson: '通っていない枝は検査されない',
  },
  {
    id: 'node-shadow-zero-mapsize',
    kind: '条件の固定',
    file: 'src/render/pipeline/nodeShadow.ts',
    find: '      if (wanted === 0 || wanted === size) return',
    replace: '      if (wanted === size) return',
    expect: 'tests/render/nodeShadow.test.ts',
    lesson: '0 を `mapSize` へ渡すと影マップが作られない',
  },
  {
    id: 'node-shadow-no-recreate',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeShadow.ts',
    find: '      light.shadow.map = null\n',
    replace: '',
    expect: 'tests/render/nodeShadow.test.ts',
    lesson: '0 を `mapSize` へ渡すと影マップが作られない',
  },
  {
    id: 'explosion-rim-stops-early',
    kind: '条件の固定',
    file: 'tools/explosion-judge.mjs',
    find: '    if (min < sky * 0.95 && v >= sky * 0.95) {',
    replace: '    if (v >= sky * 0.95) {',
    expect: 'tests/tools/explosionJudge.test.ts',
    lesson: '谷の探索が、火が空の明るさを横切る 1 画素で打ち切られていた',
  },
  {
    id: 'explosion-core-dimmest',
    kind: '比較の反転',
    file: 'tools/explosion-judge.mjs',
    find: '      if (value > best.value) best = { x, y, value }',
    replace: '      if (value < best.value || best.x < 0) best = { x, y, value }',
    expect: 'tests/tools/explosionJudge.test.ts',
    lesson: '爆発の判定道具は、芯を差分の塊の重心の 1 画素で読んでいた',
  },
  {
    id: 'explosion-core-one-pixel',
    kind: '定数の摂動',
    file: 'tools/explosion-judge.mjs',
    find: '      if ((x - cx) ** 2 + (y - cy) ** 2 > r2) continue',
    replace: '      if ((x - cx) ** 2 + (y - cy) ** 2 > 0) continue',
    expect: 'tests/tools/explosionJudge.test.ts',
    lesson: '爆発の判定道具は、芯を差分の塊の重心の 1 画素で読んでいた',
  },
  {
    id: 'fireball-inset-too-small',
    kind: '定数の摂動',
    file: 'src/render/weapons/fireballShape.ts',
    find: 'export const BALL_INSET = 1.4',
    replace: 'export const BALL_INSET = 1.2',
    expect: 'tests/render/fireballShape.test.ts',
    lesson: 'ノイズで削る輪郭が、板の四角い縁でまっすぐ切れた',
  },
  {
    id: 'blob-offset-before-ignition',
    kind: '文の削除',
    file: 'src/render/weapons/explosions.ts',
    find: '  if (blobSeconds <= 0) return 0\n',
    replace: '',
    expect: 'tests/render/explosionBlobs.test.ts',
    why: '火が付く前の子の火の玉が中心の反対側へ引き込まれる。見えないが、付いた瞬間に跳ぶ',
  },
  {
    id: 'hot-spots-no-valley',
    kind: '条件の固定',
    file: 'tools/explosion-judge.mjs',
    find: '      if (low >= avg[c] * (1 - HOT_SPOT_DIP)) {',
    replace: '      if (false) {',
    expect: 'tests/tools/explosionJudge.test.ts',
    why: '谷を見ないと、平らに明るい 1 つの火の玉を離れた画素ごとに数え、連なりが出たと読む',
  },
  {
    id: 'shard-position-aliased',
    kind: '条件の固定',
    file: 'src/render/weapons/explosions.ts',
    find: '            shardCenter,\n',
    replace: '            scratch.copy(shardCenter),\n',
    expect: 'tests/render/explosionShards.test.ts',
    lesson: '爆発の破片は、2026-08-21 の最初の実装から 1 度も画面に出ていなかった',
  },
  {
    id: 'trail-emission-forever',
    kind: '文の削除',
    file: 'src/render/weapons/explosionTrails.ts',
    find: '  if (t < 0 || t > TRAIL_EMIT_SECONDS) return 0\n',
    replace: '',
    expect: 'tests/render/explosionTrails.test.ts',
    why: '燃え尽きたあとも破片が煙を放ち、放つ前（負の時刻）の点まで濃くなる',
  },
  {
    id: 'trail-root-over-fire',
    kind: '定数の摂動',
    file: 'src/render/weapons/explosionTrails.ts',
    find: 'export const TRAIL_ROOT_FADE = { from: 0.7, to: 1.3 }',
    replace: 'export const TRAIL_ROOT_FADE = { from: -1, to: 0 }',
    expect: 'tests/render/explosionTrails.test.ts',
    why: '火の玉の中でも白い煙が濃く、火の芯の上に白い筋が乗る',
  },
  {
    id: 'trail-camera-no-fade',
    kind: '定数の摂動',
    file: 'src/render/weapons/explosionTrails.ts',
    find: 'export const TRAIL_CAMERA_FADE = { from: 20, to: 60 }',
    replace: 'export const TRAIL_CAMERA_FADE = { from: -2, to: -1 }',
    expect: 'tests/render/explosionTrails.test.ts',
    why: '近い撃墜で白い筋がカメラの手前を横切り、HUD の中央まで覆う',
  },
  {
    id: 'explosion-prewarm-invisible',
    kind: '条件の固定',
    file: 'src/render/weapons/explosions.ts',
    find: '        mesh.scale.setScalar(10)\n        mesh.visible = true\n',
    replace: '        mesh.scale.setScalar(10)\n        mesh.visible = false\n',
    expect: 'tests/render/explosionPrewarm.test.ts',
    lesson: '材質は初めて描くときに組まれ、最初の撃墜で画面が半秒止まった',
  },
  {
    id: 'augmentation-threshold',
    kind: '定数の摂動',
    file: 'src/sim/flightModel.ts',
    find: 'export const AUGMENTATION_THROTTLE = 0.85',
    replace: 'export const AUGMENTATION_THROTTLE = 0.8',
    expect: 'tests/sim/augmentation.test.ts',
    why: 'アフターバーナーの点く境目が動くと、炎の見え方と熱源（段 30b）が一緒にずれる',
  },
  {
    id: 'afterburner-heat-none',
    kind: '定数の摂動',
    file: 'src/sim/combatant.ts',
    find: 'export const AFTERBURNER_HEAT_GAIN = 0.3',
    replace: 'export const AFTERBURNER_HEAT_GAIN = 0',
    expect: 'tests/sim/exhaustIntensity.test.ts',
    why: 'アフターバーナーで熱が上がらないと、焚いたままでも遅れたフレアが効き、駆け引きが消える',
  },
  {
    id: 'flame-flicker-off',
    kind: '条件の固定',
    file: 'src/render/aircraft/afterburner.ts',
    find: '      const flicker = seconds === undefined ? 1 : flameFlicker(seconds)',
    replace: '      const flicker = 1',
    expect: 'tests/render/flameFlicker.test.ts',
    why: '炎が揺れず、アフターバーナーが止まった絵のように見える',
  },
  {
    id: 'vapor-at-cruise',
    kind: '定数の摂動',
    file: 'src/render/aircraft/vaporCone.ts',
    find: '  return smooth(0.88, 0.95, mach) * (1 - smooth(1.02, 1.1, mach))',
    replace: '  return smooth(0.5, 0.6, mach) * (1 - smooth(1.02, 1.1, mach))',
    expect: 'tests/render/vaporCone.test.ts',
    why: '巡航でもベイパーコーンが出て、機体がいつも白い輪に包まれる',
  },
  {
    id: 'hud-layout-moved',
    kind: '定数の摂動',
    file: 'src/hud/layout.ts',
    find: '  const speedTape = { x: width * 0.18, centerY: height * 0.5, halfHeight: height * 0.22 }',
    replace: '  const speedTape = { x: width * 0.19, centerY: height * 0.5, halfHeight: height * 0.22 }',
    expect: 'tests/hud/layout.test.ts',
    why: '器へ移すときに位置の式が 1 つでも変わると、基準画像が全部ずれる。元の式との一致を見張る',
  },
  {
    id: 'chase-camera-world-lag',
    kind: '文の削除',
    file: 'src/render/camera.ts',
    find: '      camera.position.copy(craftPos).add(currentOffset)\n      target.copy(craftPos).add(currentLook)\n\n',
    replace: '      target.copy(craftPos).add(currentLook)\n\n',
    expect: 'tests/render/chaseCamera.test.ts',
    why: 'カメラが機体と一緒に動かず後ろに残り、速く飛ぶほど機体が小さく遠くに写る',
  },
  {
    id: 'chase-camera-fov-widens',
    kind: '定数の摂動',
    file: 'src/render/camera.ts',
    find: 'const FOV_FAST = 42',
    replace: 'const FOV_FAST = 64',
    expect: 'tests/render/chaseCamera.test.ts',
    why: '速いほど画角が開き、機体が近づくどころか小さくなる',
  },
  {
    id: 'vapor-too-dense',
    kind: '定数の摂動',
    file: 'src/render/aircraft/vaporCone.ts',
    find: '  opacity: 0.06,',
    replace: '  opacity: 0.12,',
    expect: 'tests/render/vaporCone.test.ts',
    why: 'ベイパーコーンの膜が濃く写る',
  },
  {
    id: 'capture-settle-skipped',
    kind: '文の削除',
    file: 'src/render/pipeline/nodeBackend.ts',
    find: '      await internals.device?.queue.onSubmittedWorkDone()\n',
    replace: '',
    expect: 'tests/render/nodeBackend.test.ts',
    why: 'キャプチャの合図が GPU の描き終わりより先に出て、撮影が収束の描画を待ち CI で 60 秒を越える',
  },
  {
    id: 'score-gun-kill-unrecorded',
    kind: '文の削除',
    file: 'src/sim/combat.ts',
    find: '          this.kills++\n          this.recordKill(target)\n',
    replace: '          this.kills++\n',
    expect: 'tests/sim/combat.test.ts',
    why: '機銃で落としても SCORE が増えず、TARGET の加点も出ない',
  },
  {
    id: 'score-missile-kill-unrecorded',
    kind: '文の削除',
    file: 'src/sim/combat.ts',
    find: '        this.kills++\n        this.recordKill(target)\n',
    replace: '        this.kills++\n',
    expect: 'tests/sim/effects.test.ts',
    why: 'ミサイルで落としても SCORE が増えない',
  },
  {
    id: 'score-kill-shown-too-long',
    kind: '定数の摂動',
    file: 'src/sim/score.ts',
    find: 'export const KILL_SHOW_SECONDS = 3\n',
    replace: 'export const KILL_SHOW_SECONDS = 30\n',
    expect: 'tests/sim/score.test.ts',
    why: '撃墜の加点が 30 秒も残り、次の撃墜まで出たままになる',
  },
  {
    id: 'hud-armament-moved',
    kind: '定数の摂動',
    file: 'src/hud/layout.ts',
    find: '  const armament = { x: width * 0.94, y: height * 0.8 }',
    replace: '  const armament = { x: width * 0.84, y: height * 0.8 }',
    expect: 'tests/hud/layout.test.ts',
    why: '兵装の一覧が左へずれて高度の表示（AGL）に重なる',
  },
  {
    id: 'radar-ahead-flipped',
    kind: '符号の反転',
    file: 'src/hud/radar.ts',
    find: '  out.y = (-ahead / distance) * r\n',
    replace: '  out.y = (ahead / distance) * r\n',
    expect: 'tests/hud/radar.test.ts',
    why: 'レーダーで前の敵が下に出て、敵のいない方へ旋回させる',
  },
  {
    id: 'arrow-behind-not-flipped',
    kind: '条件の固定',
    file: 'src/hud/arrow.ts',
    find: '  const sign = point.inFront ? 1 : -1\n',
    replace: '  const sign = 1\n',
    expect: 'tests/hud/arrow.test.ts',
    why: '真後ろの敵を指すはずの矢印が前を指し、敵のいない方へ旋回させる',
  },
  {
    id: 'speed-rate-flipped',
    kind: '符号の反転',
    file: 'src/sim/aircraft.ts',
    find: '    out.speedRate = this.lastDt > 0 ? (this.speed - this.speedBefore) / this.lastDt : 0',
    replace: '    out.speedRate = this.lastDt > 0 ? (this.speedBefore - this.speed) / this.lastDt : 0',
    expect: 'tests/sim/speedRate.test.ts',
    why: '加速しているのに SPEED の箱に下向きの三角が出る',
  },
  {
    id: 'trend-no-threshold',
    kind: '比較の反転',
    file: 'src/hud/readout.ts',
    find: '  if (value > threshold) return 1\n',
    replace: '  if (value > -threshold) return 1\n',
    expect: 'tests/hud/readout.test.ts',
    why: '水平の巡航でも上向きの三角が出て、増減が読めない',
  },
  {
    id: 'radar-linear',
    kind: '文の削除',
    file: 'src/hud/radar.ts',
    find: '  return Math.sqrt(Math.min(1, Math.max(0, distance) / range))\n',
    replace: '  return Math.min(1, Math.max(0, distance) / range)\n',
    expect: 'tests/hud/radar.test.ts',
    why: 'レーダーが比例に戻り、空戦の距離（500 m）の相手が中心から 4% の所に潰れる',
  },
  {
    id: 'carrier-not-kept',
    kind: '文の削除',
    file: 'src/sim/world.ts',
    find: '    this.carrier = options.carrier ? { ...options.carrier } : null\n',
    replace: '    this.carrier = null\n',
    expect: 'tests/sim/world.test.ts',
    why: '空母のある台本でもレーダーに空母が出ない',
  },
  {
    id: 'armament-flares-unread',
    kind: '文の削除',
    file: 'src/hud/hud.ts',
    find: '      [`FLR ${armament.flares}`, armament.flares <= 0],\n',
    replace: '      [`FLR 0`, false],\n',
    expect: 'tests/hud/armament.test.ts',
    why: '器に載せただけでは出ない。HudArmament.flares は代入されているのに読む場所が無かった（計画書の段 30）',
  },
  {
    id: 'armament-missiles-unwritten',
    kind: '文の削除',
    file: 'src/main.ts',
    find: '    armament.missiles = currentWorld.combat.missilesLeft\n',
    replace: '',
    expect: 'tests/hud/armament.test.ts',
    why: 'MSL の残りが初期値の 0 のまま出て、撃てるのに尽きたように見える',
  },
  {
    id: 'carrier-render-heading-left',
    kind: '符号の反転',
    file: 'src/render/carrier.ts',
    find: '  carrier.object.rotation.set(0, -heading, 0)\n',
    replace: '  carrier.object.rotation.set(0, heading, 0)\n',
    expect: 'tests/render/carrierHeading.test.ts',
    why: '空母の絵が左回りに回り、レーダーの空母の枠と射出の向きに対して逆を向く',
  },
  {
    id: 'catapult-heading-left',
    kind: '符号の反転',
    file: 'src/sim/carrierDeck.ts',
    find: '    x * cos - z * sin,\n    x * sin + z * cos,\n',
    replace: '    x * cos + z * sin,\n    -x * sin + z * cos,\n',
    expect: 'tests/sim/carrierDeck.test.ts',
    why: '空母を回すと射出の向きだけ逆に回り、機体が甲板から外れて飛び出す',
  },
  {
    id: 'ford-mirrored',
    kind: '符号の反転',
    file: 'tools/ford-parts.mjs',
    find: '    [0, 0, -s, s * o.z],\n',
    replace: '    [0, 0, s, -s * o.z],\n',
    expect: 'tests/tools/fordParts.test.ts',
    why: '空母の glb が鏡映になり、甲板の文字が裏返って艦橋が左舷に来る',
  },
  {
    id: 'ford-cat4-skewed',
    kind: '定数の摂動',
    file: 'src/sim/fordDeck.ts',
    find: "  'cat-4': { start: [-31.321, 50.625], end: [-31.39, -52.875] },\n",
    replace: "  'cat-4': { start: [-31.321, 50.625], end: [-38.54, -52.62] },\n",
    expect: 'tests/tools/fordDeck.test.ts',
    why: '発進に使う帯が艦の軸から 4 度ずれ、射出で機体が甲板と平行に走らない（Phase 9 で直した欠陥そのもの）',
  },
  {
    id: 'mission-launch-cat1',
    kind: '定数の摂動',
    file: 'src/sim/scripts.ts',
    find: "     * 発進させたい）。段 4 では軸と平行な cat-4（斜め甲板の外側、左舷寄り）だった\n     */\n    launchFrom: 'cat-2',\n",
    replace: "     * 発進させたい）。段 4 では軸と平行な cat-4（斜め甲板の外側、左舷寄り）だった\n     */\n    launchFrom: 'cat-4',\n",
    expect: 'tests/sim/carrierDeck.test.ts',
    why: 'ミッションが甲板の中央付近ではなく斜め甲板の外側（左舷寄り）から発進する（2026-10-07 の要望）',
  },
  {
    id: 'emals-stroke-c13',
    kind: '定数の摂動',
    file: 'src/sim/launch.ts',
    find: 'export const LAUNCH_DISTANCE = 300 * 0.3048\n',
    replace: 'export const LAUNCH_DISTANCE = 94\n',
    expect: 'tests/sim/launch.test.ts',
    why: '射出の行程が Nimitz の C-13（94 m）に戻り、加速度と所要時間が EMALS の値からずれる',
  },
  {
    id: 'gear-drag-dropped',
    kind: '定数の摂動',
    file: 'src/sim/aircraft.ts',
    find: '      const cd = dragCoefficient(cl) + GEAR_DRAG_COEFFICIENT * this.gearPosition\n',
    replace: '      const cd = dragCoefficient(cl) + 0 * this.gearPosition\n',
    expect: 'tests/sim/gear.test.ts',
    why: '脚を出しても抗力が増えず、出したまま飛んでも減速しない',
  },
  {
    id: 'gear-on-deck',
    kind: '条件の固定',
    file: 'src/sim/world.ts',
    find: '    if (gearPressed && !onCatapult) this.player.toggleGear()\n',
    replace: '    if (gearPressed) this.player.toggleGear()\n',
    expect: 'tests/sim/gear.test.ts',
    why: '甲板で待つあいだに G で脚が上がる（実機は車輪に重さが掛かっていると上がらない）',
  },
  {
    id: 'gear-held-repeats',
    kind: '条件の固定',
    file: 'src/sim/world.ts',
    find: '    const gearPressed = input.gearToggle && !this.gearHeld\n',
    replace: '    const gearPressed = input.gearToggle\n',
    expect: 'tests/sim/gear.test.ts',
    why: 'G を押しっぱなしにすると毎ステップ切り替わり、脚が出たり入ったりを繰り返す',
  },
  {
    id: 'gear-label-transit-hidden',
    kind: '比較の反転',
    file: 'src/hud/readout.ts',
    find: '  if (position <= 0) return null\n',
    replace: '  if (position < 1) return null\n',
    expect: 'tests/hud/readout.test.ts',
    why: '脚が動いている途中に HUD が何も出さず、上げたつもりで出ていても気づけない',
  },
  {
    id: 'rudder-axis-vertical',
    kind: '定数の摂動',
    file: 'tools/f18e-hinges.mjs',
    find: "      to = noseCenter(v, 1, 'hi')\n",
    replace: "      to = [from[0], noseCenter(v, 1, 'hi')[1], from[2]]\n",
    expect: 'tests/tools/f18eParts.test.ts',
    why: 'ラダーを鉛直の軸で回し、外へ傾いた面の外へ振れて付け根が胴体から浮く（2026-10-07 の指摘）',
  },
  {
    id: 'aileron-axis-level',
    kind: '定数の摂動',
    file: 'tools/f18e-hinges.mjs',
    find: '      from = outer\n      to = inner\n',
    replace: '      from = outer\n      to = [inner[0], outer[1], inner[2]]\n',
    expect: 'tests/tools/f18eParts.test.ts',
    why: 'エルロンを高さ一定の軸で回し、下反角のぶん付け根側の前縁が主翼から外れる（2026-10-07 の指摘）',
  },
  {
    id: 'live-default-level',
    kind: '定数の摂動',
    file: 'src/render/capture.ts',
    find: "export const LIVE_DEFAULT_SCRIPT = 'mission-01'\n",
    replace: "export const LIVE_DEFAULT_SCRIPT = 'level'\n",
    expect: 'tests/render/captureConfig.test.ts',
    why: '公開ページが甲板からの射出でなく空中の水平飛行から始まる',
  },
  {
    id: 'nose-gear-folds-aft',
    kind: '符号の反転',
    file: 'tools/f18e-hinges.mjs',
    find: "      axis: l.leg === 'nose' ? [0, 0, -1] : [0, 0, 1],\n",
    replace: "      axis: l.leg === 'nose' ? [0, 0, 1] : [0, 0, 1],\n",
    expect: 'tests/tools/f18eParts.test.ts',
    why: '前脚が後ろへ畳まれ、脚柱が機体の中を突き抜ける（実機の F/A-18 は前へ畳む）',
  },
  {
    id: 'gear-turns-when-down',
    kind: '定数の摂動',
    file: 'src/render/aircraftView.ts',
    find: '        leg.object.quaternion.setFromAxisAngle(leg.axis, (1 - legs) * leg.retractRad)\n',
    replace: '        leg.object.quaternion.setFromAxisAngle(leg.axis, (1.1 - legs) * leg.retractRad)\n',
    expect: 'tests/render/gearLegs.test.ts',
    why: '脚を出し切っても少し畳まれたままで、甲板の上の機体が車輪で立たない',
  },
  {
    id: 'gear-struts-left-out',
    kind: '条件の固定',
    file: 'tools/f18e-parts.mjs',
    find: '  match: (p) => p.y < -0.6 || (p.y < -0.5 && p.sizeY > 0.8),',
    replace: '  match: (p) => p.y < -0.6 || (p.y < -0.5 && p.sizeY > 8),',
    expect: 'tests/tools/f18eParts.test.ts',
    why: '脚柱の上半分（185・186・195）が脚から漏れ、脚を上げても機体の下にぶら下がる（段 6 で気づいた）',
  },
  {
    id: 'stabilator-down-24',
    kind: '定数の摂動',
    file: 'tools/f18e-hinges.mjs',
    find: '  stabilator: { up: 24, down: 10.5 },\n',
    replace: '  stabilator: { up: 24, down: 24 },\n',
    expect: 'tests/tools/f18eParts.test.ts',
    why: '水平尾翼を機首下げ側にも 24 度振り、付け根の前縁が胴体の外へ大きく出る（2026-10-07 の指摘）',
  },
  {
    id: 'surfaces-one-limit',
    kind: '条件の固定',
    file: 'src/render/aircraft/surfaces.ts',
    find: '        quaternion.setFromAxisAngle(surface.axis, r * (r >= 0 ? surface.positive : surface.negative))\n',
    replace: '        quaternion.setFromAxisAngle(surface.axis, r * surface.positive)\n',
    expect: 'tests/render/surfaceLimits.test.ts',
    why: '後縁上げと後縁下げで上限が違うのに、片側の角度で両方へ振る',
  },
  {
    id: 'elevator-rate-doubled',
    kind: '定数の摂動',
    file: 'src/sim/controlSurfaces.ts',
    find: '  elevator: { positiveDeg: 24, negativeDeg: 10.5, rateDegPerSecond: 40 },\n',
    replace: '  elevator: { positiveDeg: 24, negativeDeg: 10.5, rateDegPerSecond: 80 },\n',
    expect: 'tests/sim/aircraft.test.ts',
    why: '水平尾翼が実機（40 度/秒）の 2 倍の速さで振れ、キーを押した瞬間に最大まで跳ねる',
  },
  {
    id: 'door-share-ignored',
    kind: '定数の摂動',
    file: 'src/render/aircraftView.ts',
    find: '      const open = Math.min(1, position / timing.share)\n',
    replace: '      const open = Math.min(1, position)\n',
    expect: 'tests/render/gearDoors.test.ts',
    why: '扉が脚と同じ 5 秒かけて開き、開き切る前に脚が扉を突き抜ける',
  },
  {
    id: 'main-door-shown-closed',
    kind: '条件の固定',
    file: 'src/render/aircraftView.ts',
    find: '        door.object.visible = open > 0 || !door.hideWhenClosed\n',
    replace: '        door.object.visible = true\n',
    expect: 'tests/render/gearDoors.test.ts',
    why: '閉じた主脚の扉が外板と同じ面に重なって残り、ちらつく',
  },
  {
    id: 'nose-door-height',
    kind: '定数の摂動',
    file: 'tools/f18e-doors.mjs',
    find: '      [-0.18, -0.235, -6.18],\n',
    replace: '      [-0.18, -0.335, -6.18],\n',
    expect: 'tests/tools/f18eDoors.test.ts',
    why: '前脚の扉が開口の縁より下に浮き、閉じても機体から離れて見える',
  },
  {
    id: 'msaa-high-off',
    kind: '定数の摂動',
    file: 'src/render/quality.ts',
    find: '    aircraftShadowMapSize: 1024,\n    msaaSamples: 4,\n',
    replace: '    aircraftShadowMapSize: 1024,\n    msaaSamples: 0,\n',
    expect: 'tests/render/quality.test.ts',
    why: 'high で MSAA が切れ、機体の細い溝が途切れた黒い点線に写る（2026-10-08 の指摘）',
  },
]
